### ISSUE TITLE
Allow wildcard Content-Type matching

### ISSUE THREAD

**Issue by patrickt** [tmcgilchrist/airship#106]
Currently you _have_ to provide a Content-Type if you want the `processPost` function ever to engage a `*` or unprovided Content-Type. Need to fix this for an API endpoint.

**Comment by reiddraper** [comment]
+1. This is [valid HTTP/1.1](https://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.2.1):

> Any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body. If and only if the media type is not given by a Content-Type field, the recipient MAY attempt to guess the media type via inspection of its content and/or the name extension(s) of the URI used to identify the resource. If the media type remains unknown, the recipient SHOULD treat it as type "application/octet-stream".

**Comment by patrickt** [comment]
This is fixed.
