### ISSUE TITLE
Move example executable into its own cabal file

### ISSUE THREAD

**Issue by reiddraper** [tmcgilchrist/airship#16]

**Comment by tmcgilchrist** [comment]
Happy to have a go at this, any opinions on how you'd like this done? @reiddraper

**Comment by reiddraper** [comment]
@tmcgilchrist awesome! I'd probably just suggest putting it in a subdirectory: `example`. We can then update the `stack.yaml` file to include this project as well.

**Comment by tmcgilchrist** [comment]
Think this can be closed now @reiddraper
