### ISSUE TITLE
Add Lens' w/out depending on Lens

### ISSUE THREAD

**Issue by reiddraper** [tmcgilchrist/airship#20]
https://github.com/ekmett/lens/wiki/How-can-I-write-lenses-without-depending-on-lens%3F

**Comment by tmcgilchrist** [comment]
What things would you like lenses for?

Just for things like the Request type?
https://github.com/helium/airship/blob/master/src/Airship/Types.hs#L78-L92

**Comment by reiddraper** [comment]
Yeah, `Request` and the `Resource` type are the first two that come to mind.

**Comment by patrickt** [comment]
We did this. microlens ftw
