### ISSUE TITLE
Add airship to stackage?

### ISSUE THREAD

**Issue by dysinger** [tmcgilchrist/airship#25]
You get nightly builds, notification of failures & inclusion in the LTS stackage distribution.

http://www.stackage.org/
http://www.stackage.org/authors

**Comment by reiddraper** [comment]
+1 from me.

**Comment by dysinger** [comment]
https://github.com/dysinger/airship/commit/022fd95233490fa266151860edbbc7812cced679 I've removed the version numbers in my branch & tested it with 7.10 & 7.8 with different package sets.

**Comment by dysinger** [comment]
These are package sets of nearly 1k haskell packages that work together (nightly is 900+)

**Comment by reiddraper** [comment]
@patrickt any objection from you? I'd be happy to integrate this.

**Comment by rosenk** [comment]
+1

**Comment by tmcgilchrist** [comment]
Is it a requirement to remove the version numbers for integration into stackage? @dysinger 
I've hastily submitted a PR against stackage without realising I might need to change things https://github.com/fpco/stackage/pull/933

**Comment by reiddraper** [comment]
@tmcgilchrist I'm flexible about upping or removing the upper-bounds.

**Comment by tmcgilchrist** [comment]
Removing the upper-bounds worries me, if someone changes a dependency in a non-compatible way suddenly everything breaks. Probably not as much of a problem for stack users (since there is s curated list of packages), but certainly not good for us poor cabal users.

**Comment by tmcgilchrist** [comment]
https://github.com/helium/airship/pull/65

**Comment by tmcgilchrist** [comment]
Done https://github.com/fpco/stackage/pull/970
