### ISSUE TITLE
Add handler to catch exceptions within/during the decision tree

### ISSUE THREAD

**Issue by patrickt** [tmcgilchrist/airship#26]
I'm thinking it'd be something like 

``` haskell
uncaughtException :: SomeException -> Handler s m ()
```

which would then be used in an invocation of `catch` during the decision tree's `evalState` call.

**Comment by patrickt** [comment]
With a default definition of returning 500.

**Comment by tmcgilchrist** [comment]
Have you looked at `bracket` http://hackage.haskell.org/package/exceptions-0.8.0.2/docs/Control-Monad-Catch.html ?

**Comment by reiddraper** [comment]
I wonder what this gives us that exception handling w/ Warp (or whatever Wai server you use) doesn't?

**Comment by tmcgilchrist** [comment]
I'm still reading through/understanding the airship code but mostly bracket is about better handling of asynchronous exceptions. It may or may not be appropriate here still too early to tell.

**Comment by reiddraper** [comment]
Yeah, my comment was more about this issue in general, than `bracket` in particular.

**Comment by patrickt** [comment]
Ah, I didn't see that Warp had a built-in exception handler: I thought that would've been something that WAI provided, but hey, whatever. Pity there's no abstraction over this, but yeah, all things considered let's just close this one.

**Comment by reiddraper** [comment]
Cool -- we can always revisit if needed.
