### ISSUE TITLE
No wildcard support in contentTypesProvided

### ISSUE THREAD

**Issue by dkubb** [tmcgilchrist/airship#33]
I had a resource defined with:

```
contentTypesProvided = return [("*/*", return Empty)]
```

But airship was unable to handle it. Any requests with specific `Accept` headers resulted in `406 Not Acceptable` being returned. The only case where it would work is if I passed along the _exact_ string `*/*`.

I think what should happen is that regardless of the value of the `Accept` header this should match and execute the function.

**Comment by kellymclaughlin** [comment]
I am not sure it makes sense for wildcards to be used in `contentTypesProvided`. Its purpose is to match a media type with an appropriate and specific response format. The `Accept` header from the client may use wildcards to accept any media type in response, but the types provided by an airship resource should be specific media types.

**Comment by dkubb** [comment]
What if there's no media type, as in the case of a `204 No Content`?

**Comment by kellymclaughlin** [comment]
Yeah, that's a good point. I think most resources are going to already implement `contentTypesProvided` such that this would not be an issue, but for an example, in the case of a resource that only allows DELETE and returns 204 maybe it makes sense to have either a default for `contentTypesProvided` that just works or a some way to easily say "ingore any Accept header value and just process the request".

I checked the behavior of Erlang webmachine for this case. It provides a default type of `text/html` for its `contentTypesProvided` if the resource does not implement. The simple resource that only allows DELETE and doesn not specify a `contentTypesProvided` would work with webmachine, but would not work by default with airship.

**Comment by reiddraper** [comment]
I am also not aware of any support for a _response_ having a content type of `*/*`, only through the `Accept` header.

Depending on the use-case, however, you can actually inspect the `Accept` header, and then always say that you provide whatever the user asks for.

**Comment by reiddraper** [comment]
@dkubb I'm closing this issue now, but please re-open if you think we have missed something.
