### ISSUE TITLE
Making Airship-Trace an optional header?

### ISSUE THREAD

**Issue by tmcgilchrist** [tmcgilchrist/airship#49]
It's possibly not a good idea to alway provide this header for services, exposing extra information about how the server is making decisions about what to return back.

There's 2 good solutions to make this optional:
1. Pass some configuration option into `resourceToWai` and `toWaiResponse` 
2. Provide some wai middleware that strips off the header 

Which option would you favour as the suggested solution for Airship? 
Have you run into something similar with using Airship for applications?

Happy to provide some code or examples for both options.

**Comment by reiddraper** [comment]
Let's go with adding configuration options to `resourceToWai`. I think I'd like to do something like this:

``` haskell
data AirshipConfig = ...

defaultAirshipConfig :: AirshipConfig
defaultAirshipConfig = ...

setIncludeTraceHeader :: Bool -> AirshipConfig -> AirshipConfig
setIncludeTraceHeader = ...

resourceToWai :: AirshipConfig -> RoutingSpec s IO () -> Resource s IO -> s -> Wai.Application
resourceToWai = ...
```

The basic idea being we don't expose the `AirshipConfig` constructors, the same way that [Warp doesn't](https://hackage.haskell.org/package/warp-3.1.4/docs/Network-Wai-Handler-Warp.html#t:Settings).
