### ISSUE TITLE
Per Resource State

### ISSUE THREAD

**Issue by tmcgilchrist** [tmcgilchrist/airship#66]
The current setup has a single `State` type, if you choose to use it, across all resources. So you end up with a State type that knows about all the various resources and what they want to store. Plus when you put or ask for the State, you need to know about the other values. Clearly not ideal.
e.g. 

``` haskell
data State = State { resource1 :: Text, resource2 :: Int } 
```

Ideally each resource would have private state, which got run per-resource. I've got no specific ideas right now, suggestions welcome.

**Comment by charleso** [comment]
I have _plenty_ of ideas. Many of them involve some drastic changes to the way that the decision tree works. I think the `Resource` record while nice, and matching the original `Webmachine`, is too limiting from a type perspective. I think in Haskell we can do better. :)
